server.port: 7779

spring.application.name: tester

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
