server.port: 7778

spring.application.name: client

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/